(define (problem problemGenerated_ReservesHotel) (:domain ReservesHotel)
 (:objects
	habitacio_1 	habitacio_2  - habitacio
		reserva_1 	reserva_2 	reserva_3  - reserva
		dia_1 	dia_2 	dia_3 	dia_4 	dia_5 	dia_6 	dia_7 	dia_8 	dia_9 	dia_10 	dia_11 	dia_12 	dia_13 	dia_14 	dia_15 	dia_16 	dia_17 	dia_18 	dia_19 	dia_20 	dia_21 	dia_22 	dia_23 	dia_24 	dia_25 	dia_26 	dia_27 	dia_28 	- dia
	)
	(:init
		(= (valor-dia dia_1) 1)
		(= (valor-dia dia_2) 2)
		(= (valor-dia dia_3) 3)
		(= (valor-dia dia_4) 4)
		(= (valor-dia dia_5) 5)
		(= (valor-dia dia_6) 6)
		(= (valor-dia dia_7) 7)
		(= (valor-dia dia_8) 8)
		(= (valor-dia dia_9) 9)
		(= (valor-dia dia_10) 10)
		(= (valor-dia dia_11) 11)
		(= (valor-dia dia_12) 12)
		(= (valor-dia dia_13) 13)
		(= (valor-dia dia_14) 14)
		(= (valor-dia dia_15) 15)
		(= (valor-dia dia_16) 16)
		(= (valor-dia dia_17) 17)
		(= (valor-dia dia_18) 18)
		(= (valor-dia dia_19) 19)
		(= (valor-dia dia_20) 20)
		(= (valor-dia dia_21) 21)
		(= (valor-dia dia_22) 22)
		(= (valor-dia dia_23) 23)
		(= (valor-dia dia_24) 24)
		(= (valor-dia dia_25) 25)
		(= (valor-dia dia_26) 26)
		(= (valor-dia dia_27) 27)
		(= (valor-dia dia_28) 28)
		(= (habitacio-capacitat habitacio_1) 1)
		(= (habitacio-capacitat habitacio_2) 3)
		(= (reserva-capacitat reserva_1) 3)
		(= (reserva-diaInici reserva_1) 2)
		(= (reserva-diaFi reserva_1) 3)
		(= (reserva-capacitat reserva_2) 2)
		(= (reserva-diaInici reserva_2) 1)
		(= (reserva-diaFi reserva_2) 4)
		(= (reserva-capacitat reserva_3) 1)
		(= (reserva-diaInici reserva_3) 2)
		(= (reserva-diaFi reserva_3) 5)
		(= (reserves-ateses) 0)
	)
	(:goal(forall (?r - reserva) (atessa ?r)))
	(:metric minimize (reserves-ateses))
)
